const tokens = {
  "button-text-default": "#1f1b16",
  "button-text-hover": "#f1ece0",
  "button-surface-default": "rgba(0, 0, 0, 0)",
  "button-surface-hover": "#1f1b16",
  "button-border-default": "rgba(31, 27, 22, 0.95)",
  "button-border-hover": "#1f1b16",
  "button-radius": "0px",
  "button-padding-block": "8px",
  "button-padding-inline": "12px",
  "button-typography": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":600,"fontSize":"13px","lineHeight":1.2,"letterSpacing":"-0.012em"},
  "field-text": "#1f1b16",
  "field-placeholder": "#b8ae99",
  "field-surface": "rgba(0, 0, 0, 0)",
  "field-border-default": "rgba(31, 27, 22, 0.65)",
  "field-border-focus": "#b84a39",
  "field-radius": "0px",
  "field-padding-block": "8px",
  "field-padding-inline": "12px",
  "field-typography": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":500,"fontSize":"15px","lineHeight":1.5,"letterSpacing":"-0.012em"},
  "selection-accent": "#b84a39",
  "selection-text": "#1f1b16",
  "card-surface": "rgba(244, 237, 219, 0.55)",
  "card-text": "#1f1b16",
  "card-border": "rgba(31, 27, 22, 0.65)",
  "card-radius": "0px",
  "card-padding": "16px",
  "card-typography": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":500,"fontSize":"15px","lineHeight":1.5,"letterSpacing":"-0.012em"},
  "badge-text": "#1f1b16",
  "badge-surface": "rgba(0, 0, 0, 0)",
  "badge-border": "rgba(31, 27, 22, 0.65)",
  "badge-radius": "0px",
  "badge-padding-block": "4px",
  "badge-padding-inline": "8px",
  "badge-typography": {"fontFamily":["JetBrains Mono","ui-monospace","SF Mono","Menlo","monospace"],"fontWeight":500,"fontSize":"10px","lineHeight":1,"letterSpacing":"0.08em"},
  "alert-surface": "#e4dbc4",
  "alert-text": "#1f1b16",
  "alert-border": "rgba(31, 27, 22, 0.65)",
  "alert-radius": "0px",
  "alert-padding": "16px",
  "link-text-default": "#1f1b16",
  "link-text-hover": "#b84a39",
  "link-underline-default": "rgba(31, 27, 22, 0.25)",
  "link-underline-hover": "#b84a39",
  "color-paper": "#f1ece0",
  "color-paper-warm": "#ece4d2",
  "color-paper-deep": "#e4dbc4",
  "color-ink": "#1f1b16",
  "color-ink-soft": "#4a4239",
  "color-ink-quiet": "#8a8170",
  "color-ink-faint": "#b8ae99",
  "color-red": "#b84a39",
  "color-red-soft": "#c9614f",
  "color-amber": "#d49a56",
  "color-cream-bloom": "#f4e5c7",
  "color-ink-a25": "rgba(31, 27, 22, 0.25)",
  "color-ink-a65": "rgba(31, 27, 22, 0.65)",
  "color-ink-a95": "rgba(31, 27, 22, 0.95)",
  "color-red-a85": "rgba(184, 74, 57, 0.85)",
  "color-cream-bloom-a55": "rgba(244, 237, 219, 0.55)",
  "color-cream-bloom-a85": "rgba(244, 237, 219, 0.85)",
  "color-amber-a55": "rgba(212, 154, 86, 0.55)",
  "color-amber-a18": "rgba(212, 154, 86, 0.18)",
  "color-surface-page": "#f1ece0",
  "color-surface-warm": "#ece4d2",
  "color-surface-deep": "#e4dbc4",
  "color-surface-claim": "rgba(244, 237, 219, 0.55)",
  "color-surface-claim-hover": "rgba(244, 237, 219, 0.85)",
  "color-surface-ink": "#1f1b16",
  "color-text-default": "#1f1b16",
  "color-text-soft": "#4a4239",
  "color-text-quiet": "#8a8170",
  "color-text-faint": "#b8ae99",
  "color-text-on-ink": "#f1ece0",
  "color-accent-base": "#b84a39",
  "color-accent-soft": "#c9614f",
  "color-border-default": "rgba(31, 27, 22, 0.65)",
  "color-border-quiet": "rgba(31, 27, 22, 0.25)",
  "color-border-strong": "rgba(31, 27, 22, 0.95)",
  "color-border-accent": "rgba(184, 74, 57, 0.85)",
  "space-xs": "4px",
  "space-sm": "8px",
  "space-md": "12px",
  "space-lg": "16px",
  "space-xl": "24px",
  "space-2xl": "32px",
  "space-inset": "16px",
  "space-inline-gap": "8px",
  "space-control-block": "8px",
  "space-control-inline": "12px",
  "space-badge-block": "4px",
  "space-badge-inline": "8px",
  "radius-0": "0px",
  "radius-1": "1px",
  "radius-2": "2px",
  "radius-none": "0px",
  "radius-chip": "1px",
  "radius-chip-max": "2px",
  "size-hairline": "1px",
  "size-dot": "7px",
  "size-tick": "18px",
  "size-cell-min": "120px",
  "size-page-inset": "32px",
  "size-page-left": "96px",
  "size-margin-rule-x": "56px",
  "blur-bloom": "80px",
  "blur-cursor": "18px",
  "font-sans": ["Archivo","Helvetica Neue","system-ui","sans-serif"],
  "font-mono": ["JetBrains Mono","ui-monospace","SF Mono","Menlo","monospace"],
  "weight-regular": 400,
  "weight-medium": 500,
  "weight-semibold": 600,
  "weight-bold": 700,
  "duration-bloom": "180ms",
  "duration-ui-fast": "200ms",
  "duration-ui": "240ms",
  "duration-ui-slow": "320ms",
  "duration-breathe-min": "7s",
  "duration-breathe-max": "16s",
  "duration-drift-1": "38s",
  "duration-drift-2": "51s",
  "duration-drift-3": "67s",
  "easing-paper": [0.22,0.61,0.36,1],
  "opacity-muted": 0.45,
  "motion-duration-bloom": "180ms",
  "motion-duration-hover": "200ms",
  "motion-duration-transition": "240ms",
  "motion-easing-standard": [0.22,0.61,0.36,1],
  "typography-display": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":700,"fontSize":"168px","lineHeight":0.92,"letterSpacing":"-0.04em"},
  "typography-heading-xl": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":700,"fontSize":"88px","lineHeight":0.95,"letterSpacing":"-0.035em"},
  "typography-heading-lg": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":600,"fontSize":"40px","lineHeight":1.02,"letterSpacing":"-0.028em"},
  "typography-heading-md": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":600,"fontSize":"20px","lineHeight":1.1,"letterSpacing":"-0.022em"},
  "typography-heading-sm": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":600,"fontSize":"15px","lineHeight":1.2,"letterSpacing":"-0.018em"},
  "typography-body": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":500,"fontSize":"15px","lineHeight":1.5,"letterSpacing":"-0.012em"},
  "typography-body-lg": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":500,"fontSize":"18px","lineHeight":1.45,"letterSpacing":"-0.018em"},
  "typography-body-sm": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":500,"fontSize":"13px","lineHeight":1.45,"letterSpacing":"-0.005em"},
  "typography-mark": {"fontFamily":["JetBrains Mono","ui-monospace","SF Mono","Menlo","monospace"],"fontWeight":500,"fontSize":"10px","lineHeight":1,"letterSpacing":"0.08em"},
  "typography-label": {"fontFamily":["Archivo","Helvetica Neue","system-ui","sans-serif"],"fontWeight":600,"fontSize":"13px","lineHeight":1.2,"letterSpacing":"-0.012em"},
};

export default tokens;
