// The shipped effects module: the zoo's effect generators as one dependency-free
// ESM file under built values (values/js/effects.js in the bundle), exporting the
// data primaries a framework consumer maps onto its own elements. Generated by
// concatenating the effect sources themselves — local imports fold away because
// the files are listed in dependency order and nothing is re-authored here — so
// the shipped functions are byte-for-byte the logic the zoo renders from. Only
// the data primaries are exported: the markup wrappers stay internal to the zoo,
// which renders server-side strings, while consumers render elements idiomatically.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

const EFFECTS_SOURCE_DIR = join(REPO_ROOT, 'design-system', 'source', 'zoo', 'effects');
const EFFECTS_SOURCES = [
  'deterministic-random.mjs',
  'helpers.mjs',
  'grid.mjs',
  'phyllotaxis.mjs',
  'weather-particles.mjs',
];
const EFFECTS_EXPORTS = [
  'seedHeadData',
  'growingSeedHeadData',
  'gridData',
  'windParticlesData',
  'rainParticlesData',
  'fleckParticlesData',
  'driftParticlesData',
  'fireflyParticlesData',
  'flakeParticlesData',
  'hazeParticlesData',
  'sunpoolParticlesData',
  'weatherTextData',
];

// Fold one effect source into the shipped module body: strip the local imports
// (their definitions arrive earlier in the fixed source order), drop the zoo-build
// metadata export, and de-export everything else so only the declared API below
// is public. Anything unexpected — a non-local import, an `export default`, an
// export list — fails the build rather than shipping half-understood.
function inlineEffectSource(name) {
  const src = readFileSync(join(EFFECTS_SOURCE_DIR, name), 'utf8');
  const lines = src.split('\n').flatMap((line) => {
    if (/^import\s/.test(line)) {
      if (!/from '\.\//.test(line)) {
        throw new Error(`effects module ${name}: cannot inline non-local import — ${line.trim()}`);
      }
      return [];
    }
    if (/^export const implementsRecipes\b/.test(line)) return [];
    if (/^export\s+(?!(async\s+)?(function|const|let|var)\b)/.test(line)) {
      throw new Error(`effects module ${name}: unsupported export form — ${line.trim()}`);
    }
    return [line.replace(/^export (?=(async )?(function|const|let|var)\b)/, '')];
  });
  return lines.join('\n').trim();
}

// The matching type declaration: authored here once, beside the generator that
// emits the runtime, so the two ship together and describe the same shapes.
function effectsDts() {
  return (
    '/* generated alongside effects.js from design-system/source/zoo/effects/ — do not edit by hand. */\n\n' +
    'export interface SeedDot { cx: number; cy: number; r: number; index: number }\n' +
    'export interface GrowingSeedDot { cx: number; cy: number; r: number; gi: number; index: number }\n' +
    'export interface GridCell { index: number; a: string; b: string; d: string; dl: string }\n' +
    'export interface GridField { cells: GridCell[]; cols: number; rows: number }\n' +
    '// One element of a weather field: its element class, stable index, and the CSS\n' +
    '// custom properties — in render order — that the shipped effects CSS animates it by.\n' +
    'export interface WeatherParticle { cls: string; index: number; vars: Record<string, string> }\n' +
    '// One character of hand-set weather text: the glyph and its position in the phrase.\n' +
    'export interface WeatherGlyph { char: string; index: number }\n\n' +
    'export function seedHeadData(n?: number): SeedDot[];\n' +
    'export function growingSeedHeadData(n?: number): GrowingSeedDot[];\n' +
    'export function gridData(): GridField;\n' +
    'export function windParticlesData(): WeatherParticle[];\n' +
    'export function rainParticlesData(): WeatherParticle[];\n' +
    'export function fleckParticlesData(): WeatherParticle[];\n' +
    'export function driftParticlesData(): WeatherParticle[];\n' +
    'export function fireflyParticlesData(): WeatherParticle[];\n' +
    'export function flakeParticlesData(): WeatherParticle[];\n' +
    'export function hazeParticlesData(): WeatherParticle[];\n' +
    'export function sunpoolParticlesData(): WeatherParticle[];\n' +
    'export function weatherTextData(str: string): WeatherGlyph[];\n'
  );
}

export async function emitEffectsModule(distDir) {
  const js =
    '/* generated from design-system/source/zoo/effects/ — do not edit by hand.\n' +
    "   The zoo's effect generators as one dependency-free ESM module, exporting the\n" +
    '   data primaries the markup wrappers render from. */\n\n' +
    EFFECTS_SOURCES.map(inlineEffectSource).join('\n\n') +
    `\n\nexport { ${EFFECTS_EXPORTS.join(', ')} };\n`;
  mkdirSync(join(distDir, 'js'), { recursive: true });
  writeFileSync(join(distDir, 'js', 'effects.js'), js);
  writeFileSync(join(distDir, 'js', 'effects.d.ts'), effectsDts());
  // Load-once guard: the emitted file must import cleanly and expose exactly the
  // declared data primaries — this catches any future source edit the inliner
  // cannot handle at the very moment it is made, not in a consumer's bundler.
  const mod = await import(pathToFileURL(join(distDir, 'js', 'effects.js')).href);
  const exported = Object.keys(mod);
  const missing = EFFECTS_EXPORTS.filter((name) => typeof mod[name] !== 'function');
  if (missing.length > 0 || exported.length !== EFFECTS_EXPORTS.length) {
    throw new Error(
      `emitted effects.js exposes [${exported.join(', ')}]; expected exactly [${EFFECTS_EXPORTS.join(', ')}]`,
    );
  }
}
